{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ai-proxy.fullname" . }}-secret-patcher
  labels:
    {{- include "ai-proxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ai-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ai-proxy.fullname" . }}-secret-patcher
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
