{{- if and (not .Values.oidc.existingSecret) .Values.oidc.endpoint -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-proxy.fullname" . }}-token
  labels:
    {{- include "ai-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-endpoint: {{ .Values.oidc.endpoint | quote }}
  oidc-client-id: {{ required "oidc.clientId is required when oidc.endpoint is set" .Values.oidc.clientId | quote }}
  refresh-token: {{ required "oidc.refreshToken is required when oidc.endpoint is set" .Values.oidc.refreshToken | quote }}
{{- end -}}
