apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-proxy.fullname" . }}
  labels:
    {{- include "ai-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ai-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
    - name: mgmt
      port: {{ .Values.service.mgmtPort }}
      targetPort: mgmt
      protocol: TCP
