{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-proxy.serviceAccountName" . }}
  labels:
    {{- include "ai-proxy.labels" . | nindent 4 }}
{{- end -}}
